//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAutoClassLibrary
{
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class Auto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auto()
        {
            this.Comenzi = new HashSet<Comanda>();
        }

        [DataMember]
        public int AutoId { get; set; }
        [DataMember]
        public string NumarAuto { get; set; }
        [DataMember]
        public int SasiuId { get; set; }
        [DataMember]
        public string SerieSasiu { get; set; }
        [DataMember]
        public int ClientId { get; set; }

        [DataMember]
        public virtual Sasiu Sasiu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<Comanda> Comenzi { get; set; }
        [DataMember]
        public virtual Client Client { get; set; }
    }
}
