//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAutoClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comanda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comanda()
        {
            this.DetaliiComanda = new HashSet<DetaliiComanda>();
        }
    
        public int ComandaId { get; set; }
        public int AutoId { get; set; }
        public string StareComanda { get; set; }
        public string DataSystem { get; set; }
        public string DataProgramare { get; set; }
        public string DataFinalizare { get; set; }
        public int KmBord { get; set; }
        public string Descriere { get; set; }
        public string ValoarePiese { get; set; }
    
        public virtual Auto Auto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetaliiComanda> DetaliiComanda { get; set; }
    }
}
