//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAutoClassLibrary
{
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.DetaliiComanda = new HashSet<DetaliiComanda>();
        }

        [DataMember]
        public int MaterialId { get; set; }
        [DataMember]
        public string Denumire { get; set; }
        [DataMember]
        public decimal Cantitate { get; set; }
        [DataMember]
        public decimal Pret { get; set; }
        [DataMember]
        public System.DateTime DataAprovizionare { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<DetaliiComanda> DetaliiComanda { get; set; }
    }
}
