//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAutoClassLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServiceAutoModelContainer : DbContext
    {
        public ServiceAutoModelContainer()
            : base("name=ServiceAutoModelContainer")
        {
            Configuration.LazyLoadingEnabled = false;
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auto> Autoturisme { get; set; }
        public virtual DbSet<Sasiu> Sasiuri { get; set; }
        public virtual DbSet<Mecanic> Mecanici { get; set; }
        public virtual DbSet<Material> Materiale { get; set; }
        public virtual DbSet<Imagine> Imagini { get; set; }
        public virtual DbSet<Operatie> Operatii { get; set; }
        public virtual DbSet<Comanda> Comenzi { get; set; }
        public virtual DbSet<DetaliiComanda> DetaliiComenzi { get; set; }
        public virtual DbSet<Client> Clienti { get; set; }
    }
}
