//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAutoClassLibrary
{
    using System.Runtime.Serialization;

    [DataContract]
    public enum Stare : int
    {
        [EnumMember]
        InAsteptare = 0,
        [EnumMember]
        Executata = 1,
        [EnumMember]
        RefuzataLaExecutie = 2
    }
}
