//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAutoClassLibrary
{
    using System;
    
    public enum Stare : int
    {
        InAsteptare = 0,
        Executata = 1,
        RefuzataLaExecutie = 2
    }
}
