//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAutoWpfApp.SRMecanic {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRMecanic.ISAMecanic")]
    public interface ISAMecanic {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Mecanic/GetById", ReplyAction="http://tempuri.org/IGenericServiceOf_Mecanic/GetByIdResponse")]
        ServiceAutoClassLibrary.Mecanic GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Mecanic/GetAll", ReplyAction="http://tempuri.org/IGenericServiceOf_Mecanic/GetAllResponse")]
        System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Mecanic> GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Mecanic/Add", ReplyAction="http://tempuri.org/IGenericServiceOf_Mecanic/AddResponse")]
        void Add(ServiceAutoClassLibrary.Mecanic entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Mecanic/AddRange", ReplyAction="http://tempuri.org/IGenericServiceOf_Mecanic/AddRangeResponse")]
        void AddRange(System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Mecanic> entities);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Mecanic/Remove", ReplyAction="http://tempuri.org/IGenericServiceOf_Mecanic/RemoveResponse")]
        void Remove(ServiceAutoClassLibrary.Mecanic entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Mecanic/RemoveRange", ReplyAction="http://tempuri.org/IGenericServiceOf_Mecanic/RemoveRangeResponse")]
        void RemoveRange(System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Mecanic> entities);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISAMecanicChannel : ServiceAutoWpfApp.SRMecanic.ISAMecanic, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SAMecanicClient : System.ServiceModel.ClientBase<ServiceAutoWpfApp.SRMecanic.ISAMecanic>, ServiceAutoWpfApp.SRMecanic.ISAMecanic {
        
        public SAMecanicClient() {
        }
        
        public SAMecanicClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SAMecanicClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SAMecanicClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SAMecanicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiceAutoClassLibrary.Mecanic GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Mecanic> GetAll() {
            return base.Channel.GetAll();
        }
        
        public void Add(ServiceAutoClassLibrary.Mecanic entity) {
            base.Channel.Add(entity);
        }
        
        public void AddRange(System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Mecanic> entities) {
            base.Channel.AddRange(entities);
        }
        
        public void Remove(ServiceAutoClassLibrary.Mecanic entity) {
            base.Channel.Remove(entity);
        }
        
        public void RemoveRange(System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Mecanic> entities) {
            base.Channel.RemoveRange(entities);
        }
    }
}
