//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAutoWpfApp.SRImagine {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRImagine.ISAImagine")]
    public interface ISAImagine {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Imagine/GetById", ReplyAction="http://tempuri.org/IGenericServiceOf_Imagine/GetByIdResponse")]
        ServiceAutoClassLibrary.Imagine GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Imagine/GetAll", ReplyAction="http://tempuri.org/IGenericServiceOf_Imagine/GetAllResponse")]
        System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Imagine> GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Imagine/Add", ReplyAction="http://tempuri.org/IGenericServiceOf_Imagine/AddResponse")]
        void Add(ServiceAutoClassLibrary.Imagine entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Imagine/AddRange", ReplyAction="http://tempuri.org/IGenericServiceOf_Imagine/AddRangeResponse")]
        void AddRange(System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Imagine> entities);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Imagine/Modify", ReplyAction="http://tempuri.org/IGenericServiceOf_Imagine/ModifyResponse")]
        void Modify(ServiceAutoClassLibrary.Imagine entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Imagine/Remove", ReplyAction="http://tempuri.org/IGenericServiceOf_Imagine/RemoveResponse")]
        void Remove(ServiceAutoClassLibrary.Imagine entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Imagine/RemoveRange", ReplyAction="http://tempuri.org/IGenericServiceOf_Imagine/RemoveRangeResponse")]
        void RemoveRange(System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Imagine> entities);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISAImagineChannel : ServiceAutoWpfApp.SRImagine.ISAImagine, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SAImagineClient : System.ServiceModel.ClientBase<ServiceAutoWpfApp.SRImagine.ISAImagine>, ServiceAutoWpfApp.SRImagine.ISAImagine {
        
        public SAImagineClient() {
        }
        
        public SAImagineClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SAImagineClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SAImagineClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SAImagineClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiceAutoClassLibrary.Imagine GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Imagine> GetAll() {
            return base.Channel.GetAll();
        }
        
        public void Add(ServiceAutoClassLibrary.Imagine entity) {
            base.Channel.Add(entity);
        }
        
        public void AddRange(System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Imagine> entities) {
            base.Channel.AddRange(entities);
        }
        
        public void Modify(ServiceAutoClassLibrary.Imagine entity) {
            base.Channel.Modify(entity);
        }
        
        public void Remove(ServiceAutoClassLibrary.Imagine entity) {
            base.Channel.Remove(entity);
        }
        
        public void RemoveRange(System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Imagine> entities) {
            base.Channel.RemoveRange(entities);
        }
    }
}
