//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAutoWpfApp.SRClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRClient.ISAClient")]
    public interface ISAClient {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Client/GetById", ReplyAction="http://tempuri.org/IGenericServiceOf_Client/GetByIdResponse")]
        ServiceAutoClassLibrary.Client GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Client/GetAll", ReplyAction="http://tempuri.org/IGenericServiceOf_Client/GetAllResponse")]
        System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Client> GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Client/Add", ReplyAction="http://tempuri.org/IGenericServiceOf_Client/AddResponse")]
        void Add(ServiceAutoClassLibrary.Client entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Client/AddRange", ReplyAction="http://tempuri.org/IGenericServiceOf_Client/AddRangeResponse")]
        void AddRange(System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Client> entities);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Client/Modify", ReplyAction="http://tempuri.org/IGenericServiceOf_Client/ModifyResponse")]
        void Modify(ServiceAutoClassLibrary.Client entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Client/Remove", ReplyAction="http://tempuri.org/IGenericServiceOf_Client/RemoveResponse")]
        void Remove(ServiceAutoClassLibrary.Client entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Client/RemoveRange", ReplyAction="http://tempuri.org/IGenericServiceOf_Client/RemoveRangeResponse")]
        void RemoveRange(System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Client> entities);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISAClientChannel : ServiceAutoWpfApp.SRClient.ISAClient, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SAClientClient : System.ServiceModel.ClientBase<ServiceAutoWpfApp.SRClient.ISAClient>, ServiceAutoWpfApp.SRClient.ISAClient {
        
        public SAClientClient() {
        }
        
        public SAClientClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SAClientClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SAClientClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SAClientClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiceAutoClassLibrary.Client GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Client> GetAll() {
            return base.Channel.GetAll();
        }
        
        public void Add(ServiceAutoClassLibrary.Client entity) {
            base.Channel.Add(entity);
        }
        
        public void AddRange(System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Client> entities) {
            base.Channel.AddRange(entities);
        }
        
        public void Modify(ServiceAutoClassLibrary.Client entity) {
            base.Channel.Modify(entity);
        }
        
        public void Remove(ServiceAutoClassLibrary.Client entity) {
            base.Channel.Remove(entity);
        }
        
        public void RemoveRange(System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Client> entities) {
            base.Channel.RemoveRange(entities);
        }
    }
}
