//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAutoWpfApp.SRAuto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRAuto.ISAAuto")]
    public interface ISAAuto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Auto/GetById", ReplyAction="http://tempuri.org/IGenericServiceOf_Auto/GetByIdResponse")]
        ServiceAutoClassLibrary.Auto GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Auto/GetAll", ReplyAction="http://tempuri.org/IGenericServiceOf_Auto/GetAllResponse")]
        System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Auto> GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Auto/Add", ReplyAction="http://tempuri.org/IGenericServiceOf_Auto/AddResponse")]
        void Add(ServiceAutoClassLibrary.Auto entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Auto/AddRange", ReplyAction="http://tempuri.org/IGenericServiceOf_Auto/AddRangeResponse")]
        void AddRange(System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Auto> entities);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Auto/Remove", ReplyAction="http://tempuri.org/IGenericServiceOf_Auto/RemoveResponse")]
        void Remove(ServiceAutoClassLibrary.Auto entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Auto/RemoveRange", ReplyAction="http://tempuri.org/IGenericServiceOf_Auto/RemoveRangeResponse")]
        void RemoveRange(System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Auto> entities);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISAAutoChannel : ServiceAutoWpfApp.SRAuto.ISAAuto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SAAutoClient : System.ServiceModel.ClientBase<ServiceAutoWpfApp.SRAuto.ISAAuto>, ServiceAutoWpfApp.SRAuto.ISAAuto {
        
        public SAAutoClient() {
        }
        
        public SAAutoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SAAutoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SAAutoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SAAutoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiceAutoClassLibrary.Auto GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Auto> GetAll() {
            return base.Channel.GetAll();
        }
        
        public void Add(ServiceAutoClassLibrary.Auto entity) {
            base.Channel.Add(entity);
        }
        
        public void AddRange(System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Auto> entities) {
            base.Channel.AddRange(entities);
        }
        
        public void Remove(ServiceAutoClassLibrary.Auto entity) {
            base.Channel.Remove(entity);
        }
        
        public void RemoveRange(System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Auto> entities) {
            base.Channel.RemoveRange(entities);
        }
    }
}
