//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAutoWpfApp.SRDetaliiComanda {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRDetaliiComanda.ISADetaliiComanda")]
    public interface ISADetaliiComanda {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_DetaliiComanda/GetById", ReplyAction="http://tempuri.org/IGenericServiceOf_DetaliiComanda/GetByIdResponse")]
        ServiceAutoClassLibrary.DetaliiComanda GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_DetaliiComanda/GetAll", ReplyAction="http://tempuri.org/IGenericServiceOf_DetaliiComanda/GetAllResponse")]
        System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.DetaliiComanda> GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_DetaliiComanda/Add", ReplyAction="http://tempuri.org/IGenericServiceOf_DetaliiComanda/AddResponse")]
        void Add(ServiceAutoClassLibrary.DetaliiComanda entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_DetaliiComanda/AddRange", ReplyAction="http://tempuri.org/IGenericServiceOf_DetaliiComanda/AddRangeResponse")]
        void AddRange(System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.DetaliiComanda> entities);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_DetaliiComanda/Remove", ReplyAction="http://tempuri.org/IGenericServiceOf_DetaliiComanda/RemoveResponse")]
        void Remove(ServiceAutoClassLibrary.DetaliiComanda entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_DetaliiComanda/RemoveRange", ReplyAction="http://tempuri.org/IGenericServiceOf_DetaliiComanda/RemoveRangeResponse")]
        void RemoveRange(System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.DetaliiComanda> entities);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISADetaliiComandaChannel : ServiceAutoWpfApp.SRDetaliiComanda.ISADetaliiComanda, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SADetaliiComandaClient : System.ServiceModel.ClientBase<ServiceAutoWpfApp.SRDetaliiComanda.ISADetaliiComanda>, ServiceAutoWpfApp.SRDetaliiComanda.ISADetaliiComanda {
        
        public SADetaliiComandaClient() {
        }
        
        public SADetaliiComandaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SADetaliiComandaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SADetaliiComandaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SADetaliiComandaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiceAutoClassLibrary.DetaliiComanda GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.DetaliiComanda> GetAll() {
            return base.Channel.GetAll();
        }
        
        public void Add(ServiceAutoClassLibrary.DetaliiComanda entity) {
            base.Channel.Add(entity);
        }
        
        public void AddRange(System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.DetaliiComanda> entities) {
            base.Channel.AddRange(entities);
        }
        
        public void Remove(ServiceAutoClassLibrary.DetaliiComanda entity) {
            base.Channel.Remove(entity);
        }
        
        public void RemoveRange(System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.DetaliiComanda> entities) {
            base.Channel.RemoveRange(entities);
        }
    }
}
