//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAutoWpfApp.SRComanda {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRComanda.ISAComanda")]
    public interface ISAComanda {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Comanda/GetById", ReplyAction="http://tempuri.org/IGenericServiceOf_Comanda/GetByIdResponse")]
        ServiceAutoClassLibrary.Comanda GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Comanda/GetAll", ReplyAction="http://tempuri.org/IGenericServiceOf_Comanda/GetAllResponse")]
        System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Comanda> GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Comanda/Add", ReplyAction="http://tempuri.org/IGenericServiceOf_Comanda/AddResponse")]
        void Add(ServiceAutoClassLibrary.Comanda entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Comanda/AddRange", ReplyAction="http://tempuri.org/IGenericServiceOf_Comanda/AddRangeResponse")]
        void AddRange(System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Comanda> entities);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Comanda/Remove", ReplyAction="http://tempuri.org/IGenericServiceOf_Comanda/RemoveResponse")]
        void Remove(ServiceAutoClassLibrary.Comanda entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_Comanda/RemoveRange", ReplyAction="http://tempuri.org/IGenericServiceOf_Comanda/RemoveRangeResponse")]
        void RemoveRange(System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Comanda> entities);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISAComandaChannel : ServiceAutoWpfApp.SRComanda.ISAComanda, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SAComandaClient : System.ServiceModel.ClientBase<ServiceAutoWpfApp.SRComanda.ISAComanda>, ServiceAutoWpfApp.SRComanda.ISAComanda {
        
        public SAComandaClient() {
        }
        
        public SAComandaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SAComandaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SAComandaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SAComandaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiceAutoClassLibrary.Comanda GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Comanda> GetAll() {
            return base.Channel.GetAll();
        }
        
        public void Add(ServiceAutoClassLibrary.Comanda entity) {
            base.Channel.Add(entity);
        }
        
        public void AddRange(System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Comanda> entities) {
            base.Channel.AddRange(entities);
        }
        
        public void Remove(ServiceAutoClassLibrary.Comanda entity) {
            base.Channel.Remove(entity);
        }
        
        public void RemoveRange(System.Collections.ObjectModel.ObservableCollection<ServiceAutoClassLibrary.Comanda> entities) {
            base.Channel.RemoveRange(entities);
        }
    }
}
